# Generated by Django 4.2.4 on 2023-08-27 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('polls', '0004_email_alter_post_released_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='released_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 27, 17, 30, 32, 593170)),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.IntegerField()),
                ('users', models.ManyToManyField(blank=True, related_name='addresses', to='users.person')),
            ],
        ),
    ]
